name: Deployment Development

on:
  pull_request:
    branches: [ "dev" ]
    types: closed
  workflow_dispatch:

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Get Dependencies
        run: |
          composer install --optimize-autoloader --no-dev
          php artisan route:cache
          php artisan view:cache

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          server-dir: ${{ secrets.dev_dir }}
          dry-run: true
          exclude: |
            **/.git*
            **/.git*/**
            database/**
            tests/**
            .env**
            phpunit*
            .github/**
